/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.totito;

import java.text.DecimalFormat;

/**
 *
 * @author danie
 */
public class DatosEstadisticos extends javax.swing.JFrame {

    /**
     * Creates new form DatosEstadisticos
     */
    double mediaX, mediaO, mediaDraw, varianzaX, varianzaO, varianzaDraws;
    private int winX, winO, draws, totalMatch;
    public DatosEstadisticos() {
        this.setLocationRelativeTo(null);
        
        initComponents();
        
    }
    
    public int getWinX(){
    
        return this.winX;
    
    }
    
    public void setWinX(int winX){
    
        this.winX = winX;
        LblX.setText(Integer.toString(winX));
    
    }

    public int getWinO(){
    
        return this.winO;
    
    }
    
    public void setWinO(int winO){
    
        this.winO = winO;
        LblO.setText(Integer.toString(winO));
    
    }
    
    public int getDraws(){
    
        return this.draws;
    
    }
    
    public void setDraws(int draws){
    
        this.draws = draws;
        LblDraw.setText(Integer.toString(draws));
    
    }
    
    public int getTotalMatch(){
    
        return this.totalMatch;
    
    }
    public void setTotalMatch(int totalMatch){
    
        this.totalMatch = totalMatch;
        LblTotalMatch.setText(Integer.toString(totalMatch));
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LblX = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblO = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LblDraw = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LblTotalMatch = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LblXMedia = new javax.swing.JLabel();
        LblOMedia = new javax.swing.JLabel();
        LblDrawMedia = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LblXVarianza = new javax.swing.JLabel();
        LblOVarianza = new javax.swing.JLabel();
        LblDrawVarianza = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        jLabel1.setText("X");

        LblX.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        LblX.setText("0");

        jLabel2.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        jLabel2.setText("O");

        LblO.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        LblO.setText("0");

        jLabel3.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        jLabel3.setText("Empates:");

        LblDraw.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        LblDraw.setText("0");

        jLabel4.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        jLabel4.setText("Total de partidas:");

        LblTotalMatch.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        LblTotalMatch.setText("0");

        jLabel5.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        jLabel5.setText("Victorias:");

        LblXMedia.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        LblXMedia.setText("0");

        LblOMedia.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        LblOMedia.setText("0");

        LblDrawMedia.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        LblDrawMedia.setText("0");

        jButton1.setText("Mostrar Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        jLabel6.setText("Media: ");

        jLabel7.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        jLabel7.setText("Varianza:");

        LblXVarianza.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        LblXVarianza.setText("0");

        LblOVarianza.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        LblOVarianza.setText("0");

        LblDrawVarianza.setFont(new java.awt.Font("Forte", 2, 18)); // NOI18N
        LblDrawVarianza.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel1)
                                        .addGap(56, 56, 56))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(36, 36, 36)
                                        .addComponent(LblXVarianza, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LblOVarianza, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(LblOMedia, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LblX, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(36, 36, 36)
                                        .addComponent(LblXMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(89, 89, 89)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblDraw, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblDrawMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblDrawVarianza, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblTotalMatch, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblX)
                    .addComponent(LblO)
                    .addComponent(LblDraw)
                    .addComponent(LblTotalMatch)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblXMedia)
                    .addComponent(LblOMedia)
                    .addComponent(LblDrawMedia)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblXVarianza)
                    .addComponent(LblOVarianza)
                    .addComponent(LblDrawVarianza)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DecimalFormat deci = new DecimalFormat("####.##");
        mediaX = Double.parseDouble(Integer.toString(getWinX()))/getTotalMatch();
        mediaO = Double.parseDouble(Integer.toString(getWinO()))/getTotalMatch();
        mediaDraw = Double.parseDouble(Integer.toString(getDraws()))/getTotalMatch();
        
        varianzaX = Math.pow((getWinX()-mediaX), 2)/getTotalMatch();
        varianzaO = Math.pow((getWinO()-mediaO), 2)/getTotalMatch();
        varianzaDraws = Math.pow((getDraws()-mediaDraw), 2)/getTotalMatch();
        
        LblXMedia.setText(deci.format(mediaX));
        LblOMedia.setText(deci.format(mediaO));
        LblDrawMedia.setText(deci.format(mediaDraw));
        
        LblXVarianza.setText(deci.format(varianzaX));
        LblOVarianza.setText(deci.format(varianzaO));
        LblDrawVarianza.setText(deci.format(varianzaDraws));
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosEstadisticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosEstadisticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosEstadisticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosEstadisticos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosEstadisticos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblDraw;
    private javax.swing.JLabel LblDrawMedia;
    private javax.swing.JLabel LblDrawVarianza;
    private javax.swing.JLabel LblO;
    private javax.swing.JLabel LblOMedia;
    private javax.swing.JLabel LblOVarianza;
    private javax.swing.JLabel LblTotalMatch;
    private javax.swing.JLabel LblX;
    private javax.swing.JLabel LblXMedia;
    private javax.swing.JLabel LblXVarianza;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
