/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.totito;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author NaniXC7
 */
public class Juego extends javax.swing.JFrame {

    String nextTurn = "O";
    String turn = "X";
    JLabel lbs[] = new JLabel[9];
    private int[][] win ={
        {1,2,3},
        {4,5,6},
        {7,8,9},
        {1,4,7},
        {2,5,8},
        {3,6,9},
        {1,5,9},
        {3,5,7}
    };
    
    int turns = 0;
    private boolean confirmDraw = false;
    private int contadorX = 0, contadorO = 0, contadorDraw = 0, contadorMatches = 0;
    public Juego() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        lbs[0] = Lbl_1;
        lbs[1] = Lbl_2;
        lbs[2] = Lbl_3;
        lbs[3] = Lbl_4;
        lbs[4] = Lbl_5;
        lbs[5] = Lbl_6;
        lbs[6] = Lbl_7;
        lbs[7] = Lbl_8;
        lbs[8] = Lbl_9;
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Lbl_1 = new javax.swing.JLabel();
        Lbl_2 = new javax.swing.JLabel();
        Lbl_3 = new javax.swing.JLabel();
        Lbl_6 = new javax.swing.JLabel();
        Lbl_5 = new javax.swing.JLabel();
        Lbl_4 = new javax.swing.JLabel();
        Lbl_9 = new javax.swing.JLabel();
        Lbl_8 = new javax.swing.JLabel();
        Lbl_7 = new javax.swing.JLabel();
        Lbs_Estado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Lbl_winX = new javax.swing.JLabel();
        Lbl_Draw = new javax.swing.JLabel();
        Lbl_winO = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Totito Estadística II");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        Lbl_1.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_1.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        Lbl_1.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_1.setOpaque(true);
        Lbl_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lbl_1MousePressed(evt);
            }
        });

        Lbl_2.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_2.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        Lbl_2.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_2.setOpaque(true);
        Lbl_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lbl_2MousePressed(evt);
            }
        });

        Lbl_3.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_3.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        Lbl_3.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_3.setOpaque(true);
        Lbl_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lbl_3MousePressed(evt);
            }
        });

        Lbl_6.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_6.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        Lbl_6.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_6.setOpaque(true);
        Lbl_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lbl_6MousePressed(evt);
            }
        });

        Lbl_5.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_5.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        Lbl_5.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_5.setOpaque(true);
        Lbl_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lbl_5MousePressed(evt);
            }
        });

        Lbl_4.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_4.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        Lbl_4.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_4.setOpaque(true);
        Lbl_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lbl_4MousePressed(evt);
            }
        });

        Lbl_9.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_9.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        Lbl_9.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_9.setOpaque(true);
        Lbl_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lbl_9MousePressed(evt);
            }
        });

        Lbl_8.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_8.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        Lbl_8.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_8.setOpaque(true);
        Lbl_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lbl_8MousePressed(evt);
            }
        });

        Lbl_7.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_7.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        Lbl_7.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_7.setOpaque(true);
        Lbl_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Lbl_7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(Lbl_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Lbl_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Lbl_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(Lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Lbl_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(Lbl_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Lbl_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Lbl_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, 200));

        Lbs_Estado.setBackground(new java.awt.Color(255, 255, 255));
        Lbs_Estado.setFont(new java.awt.Font("Forte", 1, 18)); // NOI18N
        Lbs_Estado.setForeground(new java.awt.Color(0, 0, 0));
        Lbs_Estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbs_Estado.setText("Turno de X");
        jPanel1.add(Lbs_Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 10, 210, 41));

        jButton1.setText("Borrar");
        jButton1.setMaximumSize(new java.awt.Dimension(114, 28));
        jButton1.setMinimumSize(new java.awt.Dimension(114, 28));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 130, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X = ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Draw = ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("O = ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        Lbl_winX.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_winX.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        Lbl_winX.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_winX.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_winX.setText("0");
        jPanel1.add(Lbl_winX, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        Lbl_Draw.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_Draw.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        Lbl_Draw.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_Draw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_Draw.setText("0");
        jPanel1.add(Lbl_Draw, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        Lbl_winO.setBackground(new java.awt.Color(255, 255, 255));
        Lbl_winO.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        Lbl_winO.setForeground(new java.awt.Color(0, 0, 0));
        Lbl_winO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lbl_winO.setText("0");
        jPanel1.add(Lbl_winO, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        jButton2.setText("Terminar Juego");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lbl_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_1MousePressed
        Presionar(1);
    }//GEN-LAST:event_Lbl_1MousePressed

    private void Lbl_2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_2MousePressed
       Presionar(2);
    }//GEN-LAST:event_Lbl_2MousePressed

    private void Lbl_3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_3MousePressed
        Presionar(3);
    }//GEN-LAST:event_Lbl_3MousePressed

    private void Lbl_4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_4MousePressed
        Presionar(4);
    }//GEN-LAST:event_Lbl_4MousePressed

    private void Lbl_5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_5MousePressed
        Presionar(5);
    }//GEN-LAST:event_Lbl_5MousePressed

    private void Lbl_6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_6MousePressed
        Presionar(6);
    }//GEN-LAST:event_Lbl_6MousePressed

    private void Lbl_7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_7MousePressed
        Presionar(7);
    }//GEN-LAST:event_Lbl_7MousePressed

    private void Lbl_8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_8MousePressed
        Presionar(8);
    }//GEN-LAST:event_Lbl_8MousePressed

    private void Lbl_9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_9MousePressed
        Presionar(9);
    }//GEN-LAST:event_Lbl_9MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        borrar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int endGame = JOptionPane.showConfirmDialog(null, "Desea terminar el juego");
        if(endGame == 0){
        
            DatosEstadisticos totalDatos = new DatosEstadisticos();
            //winX = Integer.parseInt(Lbl_winX.getText());
            totalDatos.setWinX(contadorX);
            totalDatos.setWinO(contadorO);
            totalDatos.setDraws(contadorDraw);
            totalDatos.setTotalMatch(contadorMatches);
            totalDatos.setVisible(true);
            dispose();
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public void Presionar(int Casilla){
    
        if(this.lbs[Casilla-1].getText().equals("") && !this.confirmDraw){
        
            this.lbs[Casilla-1].setText(turn);
            CambiarTurno();
            ComprobarGanador();
        
        }
        
    }
    
    public void CambiarTurno(){
    
        if(turn.equals("X")){
        
            turn = "O";
        
        }else{
        
            turn = "X";
        
        }
        
        Lbs_Estado.setText("Turno de: " + turn);
    
    }
    
    public void ComprobarGanador(){
        for (int i = 0; i < this.win.length; i++) {
                
                if(lbs[this.win[i][0]-1].getText().equals("X") &&
                    lbs[this.win[i][1]-1].getText().equals("X") &&
                    lbs[this.win[i][2]-1].getText().equals("X")){
                    
                    lbs[this.win[i][0]-1].setBackground(Color.GREEN);
                    lbs[this.win[i][1]-1].setBackground(Color.GREEN);
                    lbs[this.win[i][2]-1].setBackground(Color.GREEN);
                    Lbs_Estado.setText("El ganador es X!");
                    this.confirmDraw = true;
                    this.contadorX++;
                    this.contadorMatches++;
                    Lbl_winX.setText(Integer.toString(contadorX));
                
                }
                if(lbs[this.win[i][0]-1].getText().equals("O") &&
                            lbs[this.win[i][1]-1].getText().equals("O") &&
                            lbs[this.win[i][2]-1].getText().equals("O")){
                
                    lbs[this.win[i][0]-1].setBackground(Color.GREEN);
                    lbs[this.win[i][1]-1].setBackground(Color.GREEN);
                    lbs[this.win[i][2]-1].setBackground(Color.GREEN);
                    Lbs_Estado.setText("El ganador es O!");
                    this.confirmDraw = true;
                    this.contadorO++;
                    this.contadorMatches++;
                    Lbl_winO.setText(Integer.toString(contadorO));
                    
                
                }
                
                
        }
        
        turns++;
        
        if(turns == 9 && !this.confirmDraw){
                
                 Lbs_Estado.setText("Es un empate! :0");
                 Lbl_1.setBackground(Color.YELLOW);
                 Lbl_2.setBackground(Color.YELLOW);
                 Lbl_3.setBackground(Color.YELLOW);
                 Lbl_4.setBackground(Color.YELLOW);
                 Lbl_5.setBackground(Color.YELLOW);
                 Lbl_6.setBackground(Color.YELLOW);
                 Lbl_7.setBackground(Color.YELLOW);
                 Lbl_8.setBackground(Color.YELLOW);
                 Lbl_9.setBackground(Color.YELLOW);
                 this.contadorDraw++;
                 this.contadorMatches++;
                 Lbl_Draw.setText(Integer.toString(contadorDraw));
                    
        }
        

        
    
    }
    public void borrar(){
    
    turns = 0;
        Lbs_Estado.setText("");
        for (int i = 0; i < lbs.length; i++) {
            lbs[i].setText("");
            lbs[i].setBackground(Color.white);
        }
        
        turn = nextTurn;
        
        if(nextTurn.equals("O")){
        
            nextTurn = "X";
        
        }else{
        
            nextTurn = "O";
        
        }
        Lbs_Estado.setText("Turno de: " + turn);
        this.confirmDraw = false;
    
    }
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_1;
    private javax.swing.JLabel Lbl_2;
    private javax.swing.JLabel Lbl_3;
    private javax.swing.JLabel Lbl_4;
    private javax.swing.JLabel Lbl_5;
    private javax.swing.JLabel Lbl_6;
    private javax.swing.JLabel Lbl_7;
    private javax.swing.JLabel Lbl_8;
    private javax.swing.JLabel Lbl_9;
    private javax.swing.JLabel Lbl_Draw;
    private javax.swing.JLabel Lbl_winO;
    private javax.swing.JLabel Lbl_winX;
    private javax.swing.JLabel Lbs_Estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
